### ISSUE TITLE
NFS support on Arch Linux

### ISSUE THREAD

**Issue by xinsnake** [terrywang/vagrantboxes#12]
Thanks for creating this box and I've been using this for a while.

One thing that bothers me is that this box does not support NFS by default, which is kind of a must if you are trying to use vagrant file sharing feature. Please consider install nfs-utils and enable related services.

**Comment by root-io** [comment]
+1

**Comment by terrywang** [comment]
`nfs-utils` installed to add Synced Folder type: `NFS`.
