### ISSUE TITLE
Upgrade archlinux box for convenience

### ISSUE THREAD

**Issue by louy2** [terrywang/vagrantboxes#20]
Due to pacman 4.2 changing database format and new community package manager added to the keyring the upgrading process is not seamless.

**Comment by terrywang** [comment]
The Arch Linux x86_64 Vagrant base box is updated on a regular basis, you may have downloaded an old version of the box. The current build has pacman 4.2.1 already.

In fact, after pacman update you just need to run `pacman-db-upgrade` and it'll take care of the rest.

Have a look at `/var/log/pacman.log`, the upgrade from 4.1.2-7 to 4.2.0-5 was done on 29 December, 2014.

**Comment by louy2** [comment]
I am still using the box from [Hashicorp Atlas](https://atlas.hashicorp.com/terrywang/boxes/archlinux). How do I update without harming my existing VMs?

**Comment by terrywang** [comment]
@louy2 You need to download the box again as it has been updated a couple of times after that "release" on Atlas. Remember to always refer to [archlinux-x86_64](https://github.com/terrywang/vagrantboxes/blob/master/archlinux-x86_64.md) for the up-to-date box.
