### ISSUE TITLE
[.tmux.conf] send-prefix not bound

### ISSUE THREAD

**Issue by Araeos** [terrywang/vagrantboxes#21]
Vagrant box: Arch Linux x86_64 Base Box

I don't know if this is intended but the configuration for tmux specifies `bind C-a send-prefix` but then some lines down also `bind-key C-a last-window`.
It seems `C-a` is effectively bound to `last-window` with `send-prefix` unbound.

P.S.: What is the difference between `bind` and `bind-key`? the manual does not mention this.

**Comment by bmedicke** [comment]
There's no difference. tmux accepts shortened commands as long as they don't clash. So `bind-key`, `bind` and `bi` all work whereas `b` would clash with `break-pane`.
