### ISSUE TITLE
OEL 7 does not have puppet installed

### ISSUE THREAD

**Issue by felipe1982** [terrywang/vagrantboxes#22]
I had to run 'yum -y install puppet' in order for puppet to work. Perhaps this should be already installed in the box??

**Comment by terrywang** [comment]
The `symptom` is mentioned in [`oraclelinux-7-x86_64.md`](https://github.com/terrywang/vagrantboxes/blob/master/oraclelinux-7-x86_64.md).

The reason behind was just to keep the vagrant box as slim as possible at build time (because I used to do `chef` only).

**Comment by felipe1982** [comment]
Makes the box almost unuseable without puppet. An extra 17MB wouldn't increase download time much, and still make this box highly (re-)useable.

**Comment by terrywang** [comment]
@felipe1982 Will add it in the next update.
