### ISSUE TITLE
Request for enhancement: put these boxes to altas

### ISSUE THREAD

**Issue by stardust85** [terrywang/vagrantboxes#24]
Hello Terry. I use your boxes for my open source projects on github. I found that there is a simpler way how to share these boxes than using one's own site. It is called Atlas (by hashicorp). I hope it is free :) The nice thing is that you don't need to specify URL in your vagrantfile, you put there only e.g. terrywang/oraclelinux7 and that's it.

What do you think about it? Did you consider this option?

Thanks in advance for your response and thanks for your boxes! :+1:

**Comment by terrywang** [comment]
All the vagrant base boxes have been made available on Atlas since mid 2014.
