### ISSUE TITLE
[Arch] System no longer updates because of issue with ca-certificates-utils

### ISSUE THREAD

**Issue by proycon** [terrywang/vagrantboxes#25]
The Arch image no longer updates (``pacman -Syu``) without manual intervention because of a known issue with ``ca-certificats-utils``, see https://www.archlinux.org/news/ca-certificates-utils-20170307-1-upgrade-requires-manual-intervention/

**Comment by terrywang** [comment]
@proycon The Arch Linux vagrant base box has been updated, system is up-to-date as of 31 March 2017 (UTC+11).

**Comment by proycon** [comment]
Thanks!!
