### ISSUE TITLE
ol5 box not found

### ISSUE THREAD

**Issue by julianobarbosa** [terrywang/vagrantboxes#34]
vagrant box add ol5 http://cloud.terry.im/vagrant/oraclelinux-5-x86_64.box
getting Proxy Configuration from Host...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'ol5' (v0) for provider:
    box: Downloading: http://cloud.terry.im/vagrant/oraclelinux-5-x86_64.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by terrywang** [comment]
Oracle Linux 5 has reached end of life, it's been removed from self-hosted VPS.

Didn't expect that people are still using it. If I can find a backup I'll restore it otherwise you'll have to look for alternatives.

**Comment by terrywang** [comment]
Found a backup and uploaded to [Vagrant Cloud](https://app.vagrantup.com/terrywang/boxes/oraclelinux-5-x86_64).

Closing.
