### ISSUE TITLE
The box does not start in gui mode after changing corresponding configuration in Vagrantfile 

### ISSUE THREAD

**Issue by tkleiber** [terrywang/vagrantboxes#4]
Hi!

I have modified my Vagrantfile and uncomment following lines for booting with gui:

 config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = true
  end

But the box starts every time in headless mode?

Kind regards
Torsten Kleiber

**Comment by pantaoran** [comment]
Just wanted to note that the info about changing the init level above is outdated for Oracle Linux 7.
This system now uses Systemd as init system, and instead of changing /etc/inittab you would type the following:

# systemctl set-default graphical.target

**Comment by MostafaElKatoury** [comment]
"On servers, we DO NOT need Desktop Environment (minimize system as a general security best practice)"
i have a question as I got confused , is this means that the VMs generated using vagrant are only for servers not desktops, forexamlpe if I want to code or use any IDEs to depug , run ... , VMs generated from vagrant aren't the right place to code ,  would you clarify this point as I started to implement my dev desktop enviorment not server.
